### ISSUE TITLE
check all changes to SLH-DSA after 3rd round are incorporated

### ISSUE THREAD

**Issue by falko-strenzke** [pqc-thunderbird/libgcrypt#58] opened 2024-02-06 08:41 UTC
for the list of changes, see: https://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.205.ipd.pdf#page=12

**Comment by TJ-91** [comment] 2024-02-15 13:40
Indeed, I missed / wrongly dismissed PR 51 of https://github.com/sphincs/sphincsplus/

I fixed this and updated the test vectors in the all-pqc branch.

The issue is brought up on the mailing list here https://groups.google.com/a/list.nist.gov/g/pqc-forum/c/88tuvtb7nN4/m/DA1QCoJWBAAJ andit doesn't seem to be fully resolved, at least the PR is not merged to main yet and there might be further changes in the future.

**Closed as completed** 2024-05-02 07:58 UTC
Labels: test, SLH-DSA
